apiVersion: v1
kind: Pod
metadata:
  name: multi-container-demo
spec:
  containers:
    - name: alpine-container
      image: alpine
      command: ["sh", "-c", "while true; do echo Hello from Alpine; sleep 5; done"]

    - name: tomcat-container
      image: tomcat:9.0
      ports:
        - containerPort: 8080
